name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ble-lan-frontend:${{ github.sha }}
#    - name: Test Container execution
#      run: timeout --preserve-status 10 docker run --rm --name ble_lan_frontend -p 80:4200 ble-lan-frontend:${{ github.sha }}
    - name: Finish
      run: echo "FINISHED"
